-- 01_schema.sql
-- Create user and tables for Loan Origination Sample

-- Switch to a writable PDB if present
DECLARE
  v_pdb VARCHAR2(128);
BEGIN
  SELECT name
    INTO v_pdb
    FROM v$pdbs
   WHERE name NOT IN ('PDB$SEED')
   ORDER BY name
   FETCH FIRST 1 ROWS ONLY;
  EXECUTE IMMEDIATE 'ALTER SESSION SET CONTAINER = ' || v_pdb;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
END;
/

-- Create User
-- Drop if exists (optional, but good for reset)
BEGIN
   EXECUTE IMMEDIATE 'DROP USER loan_user CASCADE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1918 THEN
         RAISE;
      END IF;
END;
/

CREATE USER loan_user IDENTIFIED BY "Welcome12345!";
GRANT CONNECT, RESOURCE TO loan_user;
ALTER USER loan_user QUOTA UNLIMITED ON USERS;

-- Create Tables
CREATE TABLE loan_user.applications (
    id VARCHAR2(50) PRIMARY KEY,
    status VARCHAR2(50) NOT NULL,
    applicant_data CLOB,
    decision_data CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_user.audit_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id VARCHAR2(50),
    action VARCHAR2(100),
    details CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_user.idempotency_keys (
    idempotency_key VARCHAR2(100) NOT NULL,
    route_path VARCHAR2(100) NOT NULL,
    payload_hash VARCHAR2(64) NOT NULL,
    request_mode VARCHAR2(50),
    execution_mode VARCHAR2(50),
    status VARCHAR2(20) NOT NULL,
    response_code NUMBER,
    response_body CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_idempotency PRIMARY KEY (idempotency_key, route_path)
);

-- Grant access to tables if needed (user is owner, so explicit grants not needed for self)

EXIT;
